# Generated by Django 4.0.3 on 2022-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeta', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='username',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
