# Generated by Django 4.0.3 on 2022-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeta', '0003_email_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
